name: pulsegrid_analytics
version: 1.0.0
config-version: 2

profile: pulsegrid_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  pulsegrid_analytics:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts
